Description: CloudFormation template for initializing AWS IAM
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  AdminUserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: AdminUserGroup
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  PowerUserUserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: PowerUserUserGroup
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
  ReadOnlyUserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: ReadOnlyUserGroup
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
  CloudformationUserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: CloudformationUserGroup
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
  CommonUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: NonAdminUserPolicy
      Groups:
        - !Ref ReadOnlyUserGroup
        - !Ref PowerUserUserGroup
        - !Ref AdminUserGroup
        - !Ref CloudformationUserGroup
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - iam:ChangePassword
Outputs:
  TemplateID:
    Description: "Template id."
    Value: "security/account-password-policy"
  TemplateVersion:
    Description: "Template version."
    Value: "__VERSION__"
  StackName:
    Description: "Stack name."
    Value: !Sub "${AWS::StackName}"
  AdminUserGroup:
    Description: "Admin user group ARN."
    Value: !Ref AdminUserGroup
  ReadOnlyUserGroup:
    Description: "Read only user group ARN."
    Value: !Ref ReadOnlyUserGroup
  CloudformationUserGroup:
    Description: "Cloudformation user group ARN."
    Value: !Ref CloudformationUserGroup
  PowerUserUserGroup:
    Description: "Power user user group ARN."
    Value: !Ref PowerUserUserGroup
